NART_VERSION := `cat VERSION`
NART_VERSION_MAJOR := $(word 1,$(subst ., ,$(NART_VERSION)))
NART_VERSION_MINOR := $(word 2,$(subst ., ,$(NART_VERSION)))
NART_VERSION_PATCH := $(word 3,$(subst ., ,$(NART_VERSION)))

CFLAGS += -DNART_VERSION_MAJOR=$(NART_VERSION_MAJOR)
CFLAGS += -DNART_VERSION_MINOR=$(NART_VERSION_MINOR)
CFLAGS += -DNART_VERSION_PATCH=$(NART_VERSION_PATCH)
