/*
 * Copyright 2022 SenseTime Group Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OP_TP_H
#define OP_TP_H

#define OP_GROUP_CODE_DEFAULT    0x0000l
#define OP_GROUP_CODE_PLUS       0x0001l
#define OP_GROUP_CODE_CUDA       0x0002l
#define OP_GROUP_CODE_QUANT      0x0006l
#define OP_GROUP_CODE_TENSORRT   0x000Dl
#define OP_GROUP_CODE_CUDA_QUANT 0x000Fl

#define OP_DECLARE(op_group, code) (((uint64_t)op_group << 32) | (code))

/* reserve 0x0001 - 0xfffe for general op types */
#define OP_NONE  OP_DECLARE(OP_GROUP_DEFAULT, 0x00000000)
#define OP_ERROR OP_DECLARE(OP_GROUP_DEFAULT, 0xffffffff)

/* ------ define default group ------ */
/* unary */
#define OP_SQRT OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0001l)
#define OP_LOG  OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0002l)
#define OP_EXP  OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0003l)

/* binary */
#define OP_ADD    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0011l)
#define OP_SUB    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0012l)
#define OP_MUL    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0013l)
#define OP_DIV    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0014l)
#define OP_MATMUL OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0015l)
#define OP_POW    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0016l)

/* nn */
#define OP_CONV_2D          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0100l)
#define OP_RELU             OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0101l)
#define OP_POOL             OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0102l)
#define OP_LRN              OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0103l)
#define OP_IP               OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0104l)
#define OP_BN               OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0105l)
#define OP_CONCAT           OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0106l)
#define OP_SLICE            OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0107l)
#define OP_DECONV_2D        OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0108l)
#define OP_INTERP           OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0109l)
#define OP_SIGMOID          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x010Al)
#define OP_SOFTMAX          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x010Bl)
#define OP_ELTWISE          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x010Cl)
#define OP_SCALE            OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x010Dl)
#define OP_RESHAPE          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x010El)
#define OP_SUBPIXEL         OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x010Fl)
#define OP_PRELU            OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0110l)
#define OP_PSROIPOOLING     OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0111l)
#define OP_ROIALIGNPOOLING  OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0112l)
#define OP_TANH             OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0113l)
#define OP_TRANSPOSE        OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0114l)
#define OP_CONV_2D_WINO     OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0115l)
#define OP_HEATMAP2COORD    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0116l)
#define OP_EXCHANGE         OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0117l)
#define OP_CORRELATION      OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0118l)
#define OP_ROIPOOLING       OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0119l)
#define OP_PSROIMASKPOOLING OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x011Al)
#define OP_BILATERALSLICE   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x011Bl)
#define OP_DEFORM_CONV_2D   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x011Cl)
#define OP_SHUFFLECHANNEL   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x011Dl)
#define OP_RELU6            OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x011El)

#define OP_BATCHNORM OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x011Fl)

#define OP_PSROIALIGNPOOLING OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0120l)
#define OP_QUANT_DEQUANT     OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0121l)

#define OP_PAD                OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0123l)
#define OP_PODROIALIGNPOOLING OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0124l)

#define OP_INSTANCENORM OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0125l)
#define OP_REDUCEMIN    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0126l)
#define OP_REDUCEMAX    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0127l)
#define OP_REDUCEMEAN   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0128l)
#define OP_REDUCEPROD   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0129l)

#define OP_CORRELATION1D   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x012Al)
#define OP_LPNORMALIZATION OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x012Bl)
#define OP_GATHER          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x012Cl)
#define OP_ARGMAX          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x012Dl)
#define OP_GRIDSAMPLE      OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x012El)
#define OP_UNFOLD          OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x012Fl)

#define OP_REDUCESUM       OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0130l)
#define OP_REDUCESUMSQUARE OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0131l)
#define OP_REDUCEL2        OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0132l)

#define OP_TOPK OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0133l)

#define OP_ABS   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0134l)
#define OP_FLOOR OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0135l)

#define OP_LSTM OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0136l)

#define OP_HARDSIGMOID OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0137l)
#define OP_ERF         OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0138l)
#define OP_CLIP        OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0139l)
#define OP_CAST        OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0140l)

#define OP_CONV_ND   OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0141l)
#define OP_HSWISH    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0142l)
#define OP_SCATTERND OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0143l)

#define OP_MIN      OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0144l)
#define OP_LESS     OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0145l)
#define OP_WHERE    OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0146l)
#define OP_SIGN     OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0147l)
#define OP_ROUNDTO0 OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0148l)
#define OP_ELU      OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0149l)

#define OP_CLIP_CAST         OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0150l)
#define OP_ADD_DIV_CLIP_CAST OP_DECLARE(OP_GROUP_CODE_DEFAULT, 0x0151l)
/* ------ end define default group ------ */
#endif // OP_TP_H
