file(READ "VERSION" NART_VERSION_FULL)
string(REPLACE "\n" "" NART_VERSION_FULL "${NART_VERSION_FULL}")

string(REPLACE "-" "" NART_VERSION "${NART_VERSION_FULL}")

string(REPLACE "." ";" NART_VERSION_PARTS "${NART_VERSION}")

list(GET NART_VERSION_PARTS 0 NART_VERSION_MAJOR)
list(GET NART_VERSION_PARTS 1 NART_VERSION_MINOR)
list(GET NART_VERSION_PARTS 2 NART_VERSION_PATCH)

add_definitions(
    -DNART_VERSION_MAJOR=${NART_VERSION_MAJOR}
    -DNART_VERSION_MINOR=${NART_VERSION_MINOR}
    -DNART_VERSION_PATCH=${NART_VERSION_PATCH}
)
