name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.3.1'
          method: network
      - name: Install other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcublas-dev-11-3 libcudnn8-dev tensorrt-dev
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nart
          environment-file: .github/conda/build-environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true
          python-version: 3.7
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Build NART
        shell: bash -l {0}
        run: |
          cmake -B build -DNART_CASE_MODULES='quant;cuda;tensorrt;cuda_quant' -DENABLE_NART_TOOLS=ON
          cmake --build build
      - name: Install NART
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib
          cmake --install build --prefix $CONDA_PREFIX
          cd python
          python setup.py install
